export const supplierMockExample = {
  transactionId: '8C8D8541553211EEE2D08E3B3B3F9',
  orderId: '1234567',
  currency: 'BRL',
  operationValue: 38639,
  chargeProcessingFee: false,
  chargebackLiable: false,
  proportionalRefund: 'false',
  miniCart: {
    items: [
      {
        id: '76671',
        name: 'Mocked Item',
        value: 0,
        quantity: 1,
        // priceTags: [],
        components: undefined,
        commission: 0,
        freightCommission: 0,
        sellerChain: undefined,
        shippingDiscount: 0,
        discount: 0,
        refId: undefined,
        productId: undefined,
        sellingPrice: 0,
        sellerId: undefined,
        dockId: undefined,
        categoryId: undefined,
        categoryName: undefined,
        catergoryName: undefined,
        deliveryChannel: undefined,
        deliveryType: undefined,
        deliverySlaInMinutes: undefined,
        deliveryWindow: undefined,
        tax: 0,
        freight: 0,
      },
    ],
    freight: 1739,
    orderUrl: 'http://www.someaccount.com/admin/checkout/#/orders?q=10000',
    tax: 0,
    shippingdate: undefined,
    shippingestimated: '2bd',
    isGiftRegistry: undefined,
    giftRegistryDescription: undefined,
    giftRegistryId: undefined,
    isPickupStore: undefined,
    isCallCenter: undefined,
  },
}
